config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "movies#index"
  get "/movies", to: "movies#index"

  get "", to: "movies#index"
  post "movies", to: "movies#create"

  get "/buscar", to: "movies#show"

  get "", to: "reservations#index"
  get "/movies", to: "reservations#index"
  get "/listaReservation", to: "reservations#show"
  get "/listaReservas", to: "reservations#mostrarReservas"
  

  post "reservations", to: "reservations#create"
  
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :reservations

    
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
    @peliculaNueva = Movie.new
  end

  
  def create 
    
    @peliculaCreada = Movie.create(titulo: params[:movie][:titulo], sinopsis: params[:movie][:sinopsis], url: params[:movie][:url], estreno: params[:movie][:estreno], fin: params[:movie][:fin])
    if @peliculaCreada.save
      redirect_to action: :index, notice: "se creo la pelicula."
      
    else
      
      render :flash => { :success => "No se creo la pelicula" }
      # redirect_to action: :index, notice: "se creo la pelicula."
    end
  end

  
  

  def show
    @movies = Movie.all
    
    @fechas = params[:date1]
    
    @arregloPeliculas = []
    @movies.each do |x|
      if x.estreno <= @fechas && x.fin > @fechas 
         @arregloPeliculas << x
      end
      
    end
    # @movies = Movie.find(params[:date1] [:date2])
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  
  def index
    @reservaNueva = Reservation.new
  end
  def show
    @listaReservation = Reservation.all
    @pelicula = Movie.all


  end
  
  def mostrarReservas
    @listaReservation = Reservation.all
    @fechaBuscada = params[:dateReservation]
    @pelicula = Movie.all

    @arregloReserva = []
    @listaReservation.each do |x|
      if x.fechaReserva == @fechaBuscada
         @arregloReserva << x
      end
      
    end
  end

  def contador(idPelicula, fr, contador)
    @listaReservation = Reservation.all
    
    @listaReservation.each do |x|
      if x.movie_id.to_s == idPelicula.to_s && x.fechaReserva == fr
        contador += 1
      end
    end
    return contador

  end

  def texto(idPelicula, fr, contador)
    @listaReservation = Reservation.all
    @listaReservation.each do |x|
    
      if x.fechaReserva == fr && x.movie_id.to_s == idPelicula.to_s 
        contador += 1 
      end
    end
    return contador

  end

  def create
    
    @listaReservation = Reservation.all
    @contador = 0
    @idPelicula = params[:reservation][:movie_id]
    @fr = params[:reservation][:fechaReservation]
    hola = texto(@idPelicula, @fr, @contador)
    
    
    
    if contador(@idPelicula, @fr, @contador) < 10
      @reservaNueva = Reservation.create(nombre: params[:reservation][:nombre], cedula: params[:reservation][:cedula], celular: params[:reservation][:celular], correo: params[:reservation][:correo], movie_id: @idPelicula, fechaReserva: params[:reservation][:fechaReservation] )
      if @reservaNueva.save
        redirect_to action: :show, notice: "#{hola}"
      else
        redirect_to action: :index, notice: "no se pudo crear la reserva"
      end
    else
      redirect_to action: :index, notice:"no hay sillas dispobibles para la funcion"
    end 
    
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/layouts/_header.html.erb
<section id="sideMenu">
    <div class="logo">
      <%= image_tag("logo.png", :alt => "logo feed", :width => "170px", :height => "180px") %>
					
    </div>
        <nav>
          <a href="/listaReservation" class=""><i class="far fa-calendar-plus fa" aria-hidden="true"></i>Reservas</a>
          <a href="/movies"><i class="fas fa-film fa" aria-hidden="true"></i>Peliculas</a>
          
        </nav>

  </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProyectoPeliculas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/806209427b.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200&display=swap" rel="stylesheet">
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </head>

  <body style="font-family: 'Montserrat', sans-serif;">
    
  <%= render "layouts/header" %>
  
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<header>

<div class="search-area">
    <h1>Peliculas</h1>
</div>
<div class="user-area">
    <a id="btnmodal" class="btn btn-info "><i class="far fa-plus-square fa" aria-hidden="true"></i>Crear Nueva Pelicula</a>
</div>


</header>

<div class="encabezado">
  
  <%= form_tag("/buscar", method: "get") do %>
    <b><%= label_tag(:q, "Seleccione Fechas:") %></b>
    <%= date_field_tag(:date1, placeholder = Date.today)%>
    <%= submit_tag("Buscar") %>
  <% end %>
  
</div><br>

<div class="cuerpoPeliculas">
  <% @movies.each do |movies| %>
    <div id="<%= movies.id %>" onclick="agregarId(<%= movies.id %><%= @fechas %>)" class="cuadroPelicula" style="background-image: url(<%= movies.url %>); background-size: 100% 100%;background-repeat: no-repeat;height: 348px;width: 23%;float: left; margin: 10px"></div>
  
  <% end %>

  <div class="cuerpo"></div>
  <div class="hola1"></div>
</div>





  
 <div class="modal fade" id="ModalForm" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="border-radius:25px">
      <div class="modal-header">
        <h5 class="modal-title lt" id="exampleModalLabel" href="">Crear Pelicula</h5>
        <button id="closeModal" type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with model: @peliculaNueva do |form| %>
        <div>
          <%= form.label :titulo, :class => "letra" %><br>
          <%= form.text_field :titulo, :class => "form-control pn"%>
        </div>

        <div>
          <%= form.label :sinopsis, :class => "letra" %><br>
          <%= form.text_area :sinopsis, :class => "form-control pn"%>
        </div>
        <div>
          <%= form.label :url, :class => "letra" %><br>
          <%= form.text_area :url, :class => "form-control pn"%>
        </div>
        <div>
          <%= form.label :estreno, :class => "letra" %><br>
          <%= form.date_field :estreno, :class => "form-control pn"%>
        </div>
        <div>
          <%= form.label :fin, :class => "letra" %><br>
          <%= form.date_field :fin, :class => "form-control pn"%>
        </div>
        <br>
        <div class="modal-footer">
          <button id="btncloseModal" type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
          <%= form.submit :'Crear Nueva Pelicula', :class => "btn-info botonEnviar"%>
        </div>
      <% end %>
        
      </div>
      
    </div>
  </div>
</div>



<script type="text/javascript">
$("#btnmodal").click(function() {
    $("#ModalForm").modal('show')
});

$("#btncloseModal, #closeModal").click(function() {
    $("#ModalForm").modal('hide')
});

// $(".cuadroPelicula").click(function() {
//     $("#ModalFormReservaton").modal('show')
    
// });

// $("#btncloseModalR, #closeModalR").click(function() {
//     $("#ModalFormReservaton").modal('hide')
// });

function agregarId(idmovie, date){
  $("#movie_id").val(idmovie)
  $("#fechaReservation").val(date)

}


</script>

app/views/movies/show.html.erb
<header>

<div class="search-area">
    <h1>Peliculas</h1>
</div>

</header>
<div class="encabezado">
  
  <%= form_tag("/buscar", method: "get") do %>
    <b><%= label_tag(:q, "Seleccione Fechas:") %></b>
    <%= date_field_tag(:date1, placeholder = @fechas) %>
    <%= submit_tag("Buscar") %>
  <% end %>
  
</div><br>

<div class="cuerpoPeliculas">
  <% @arregloPeliculas.each do |movies| %>
    <div id="<%= movies.id %>" onclick="agregarId(<%= movies.id %>, <%= @fechas %>)" class="cuadroPelicula" style="background-image: url(<%= movies.url %>); background-size: 100% 100%;background-repeat: no-repeat;height: 348px;width: 23%;float: left; margin: 10px"></div>
      
  <% end %>

  <div class="cuerpo"></div>
  <div class="hola1"></div>
</div> 

<div class="modal fade" id="ModalFormReservaton" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="border-radius:25px">
      <div class="modal-header">
        <h5 class="modal-title lt" id="exampleModalLabel" href="">Reservar</h5>
        <button id="closeModalR" type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

      <%= form_tag reservations_path do %>
      
        <label class="letra">Nombre completo</label><br>
        <input type="text" id="post_nombre" name="reservation[nombre]" class ="form-control"><br>
      
        <label class="letra">Cedula</label><br>
        <input type="text" id="post_cedula" name="reservation[cedula]" class ="form-control"><br>
        <label class="letra">Celular</label><br>
        <input type="text" id="post_celular" name="reservation[celular]" class ="form-control"><br>
        <label class="letra">Correo</label><br>
        <input type="text" id="post_correo" name="reservation[correo]" class ="form-control"><br>
  
        <input type="number" id="movie_id" name="reservation[movie_id]" style="display:none"><br>

        <%=date_field_tag 'reservation[fechaReservation]',  @fechas, class: 'special_input fechaOculta', disabled: false%>
        <div class="modal-footer">
           <button id="btncloseModalR" type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
          <input type="submit" value="Reservar Ahora" class="btn-info botonEnviar">
        </div>
      <% end %>
       
      </div>
      
    </div>
  </div>
</div>


<script type="text/javascript">


$(".cuadroPelicula").click(function() {
    $("#ModalFormReservaton").modal('show')
    
});

$("#btncloseModalR, #closeModalR").click(function() {
    $("#ModalFormReservaton").modal('hide')
});

function agregarId(idmovie, fecha){
  
  $("#movie_id").val(idmovie)
  $("#fechaReservation").val(fecha)

}
</script>

app/views/reservations/index.html.erb
<h1>Reservations#index</h1>
<p>Find me in app/views/reservations/index.html.erb</p>

app/views/reservations/mostrarReservas.html.erb
<header>

<div class="search-area">
    <h1>Reservas Realizadas</h1>
</div>

</header>
<div class="encabezado re">
  
  <%= form_tag("/listaReservas", method: "get") do %>
    <b><%= label_tag(:q, "Seleccione Fechas:") %></b>
    <%= date_field_tag(:dateReservation, placeholder = @fechaBuscada) %>
    <%= submit_tag("Search") %>
  <% end %>
  
</div><br>

<div class="cuerpoPeliculas re">
  
    <table class="table letra">
        <thead>
            <tr>
                <td>Pelicula</td>
                <td>Nombre</td>
                <td>Cedula</td>
                <td>Celular</td>
                <td>Correo</td>
                
            </tr>
        </thead>
        <tbody>
            
            <% @arregloReserva.each do |reserva| %>
            <% peliculaEncontrada = ""%>
                <% @pelicula.each do |peli| %>
                
                    <% if(peli.id == reserva.movie_id)%>
                        <% peliculaEncontrada = peli.titulo%>
                    <% end %>
                <% end %>
                <tr>
                    <td><%=peliculaEncontrada%></td>
                    <td><%=reserva.nombre%></td>
                    <td><%=reserva.cedula%></td>
                    <td><%=reserva.celular%></td>
                    <td><%=reserva.correo%></td>
                    <td><%=reserva.fechaReserva%></td>
                    
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/reservations/show.html.erb
<header>

<div class="search-area">
    <h1>Reservas realizadas</h1>
</div>



</header>

<div class="encabezado re">
  
  <%= form_tag("/listaReservas", method: "get") do %>
    <b><%= label_tag(:q, "Seleccione la Fecha:") %></b>
    <%= date_field_tag(:dateReservation)%>
    <%= submit_tag("Search") %>
  <% end %>
  
</div><br>

<div class="cuerpoPeliculas re">
  
    <table class="table letra">
        <thead>
            <tr>
                <td>Pelicula</td>
                <td>Nombre Reservante</td>
                <td>Cedula</td>
                <td>Celular</td>
                <td>Correo</td>
                
            </tr>
        </thead>
        <tbody>
            
            <% @listaReservation.each do |reser| %>
            <% peliculaEncontrada = ""%>
                <% @pelicula.each do |peli| %>
                    <% if(peli.id == reser.movie_id)%>
                        <% peliculaEncontrada = peli.titulo%>
                    <% end %>
                <% end %>
                <tr>
                    <td><%=peliculaEncontrada%></td>
                    <td><%=reser.nombre%></td>
                    <td><%=reser.cedula%></td>
                    <td><%=reser.celular%></td>
                    <td><%=reser.correo%></td>
                </tr>
            <% end %>
        </tbody>
    </table>
  

  <div class="cuerpo"></div>
  <div class="hola1"></div>
</div>